paths:
  /api/products/mockingproducts:
    get:
      summary: Obtiene productos simulados (mock)
      tags:
        - Products
      responses:
        '200':
          description: Productos simulados obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        '500':
          description: Error del servidor. Ocurrió un error inesperado en el servidor.

  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        '200':
          description: Productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        '500':
          description: Error del servidor. Ocurrió un error inesperado en el servidor.

  '/api/products/{id}':
    get:
      summary: Obtiene un producto por ID
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: ID del producto que se busca
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        '500':
          description: Error del servidor. Ocurrió un error inesperado en el servidor.
